import { Book } from "./types";

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Thus Spoke Zarathustra',
    author: 'Friedrich Nietzsche',
    cover: 'https://m.media-amazon.com/images/I/81uJNoHnXvL.jpg',
    states: 'reading',
    rating: 5,
    tags: ['Philosophy', 'Nietzsche'],
    startedAt: new Date('2024-03-10'),
  },
  {
    id: '2',
    title: 'Beyond Good and Evil',
    author: 'Friedrich Nietzsche',
    cover: 'https://images.cdn2.buscalibre.com/fit-in/360x360/63/b6/63b6da7aa3c425fb4c1e265d2dec94e0.jpg',
    states: 'read',
    rating: 5,
    tags: ['Philosophy', 'Nietzsche'],
    finishedAt: new Date('2024-02-15'),
  },
  {
    id: '3',
    title: 'The Myth of Sisyphus',
    author: 'Albert Camus',
    cover: 'https://images.cdn1.buscalibre.com/fit-in/360x360/4f/18/4f18dced5ffb669121a409d3d5e99702.jpg',
    states: 'want_to_read',
    rating: null,
    tags: ['Philosophy', 'Camus', 'Existentialism'],
  },
  {
    id: '4',
    title: 'Fear and Trembling',
    author: 'Søren Kierkegaard',
    cover: 'https://m.media-amazon.com/images/I/51X1qExl0tL._UF1000,1000_QL80_.jpg',
    states: 'read',
    rating: 4,
    tags: ['Philosophy', 'Kierkegaard', 'Existentialism'],
    finishedAt: new Date('2023-11-20'),
  },
  {
    id: '5',
    title: 'Republic',
    author: 'Plato',
    cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOaABp5gUQcLxdZhdYe_IOr39zqJBqKDLImA&s',
    states: 'read',
    rating: 5,
    tags: ['Philosophy', 'Plato', 'Classics'],
    finishedAt: new Date('2023-09-01'),
  },
  {
    id: '6',
    title: 'Nicomachean Ethics',
    author: 'Aristotle',
    cover: 'https://m.media-amazon.com/images/I/91kcvwu5GlL.jpg',
    states: 'want_to_read',
    rating: null,
    tags: ['Philosophy', 'Aristotle', 'Ethics'],
  },
  {
    id: '7',
    title: 'The Birth of Tragedy',
    author: 'Friedrich Nietzsche',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1429743385i/2823.jpg',
    states: 'read',
    rating: 5,
    tags: ['Philosophy', 'Nietzsche'],
    finishedAt: new Date('2024-01-05'),
  },
  {
    id: '8',
    title: 'The Stranger',
    author: 'Albert Camus',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1738704267i/49552.jpg',
    states: 'read',
    rating: 5,
    tags: ['Philosophy', 'Camus', 'Existentialism'],
    finishedAt: new Date('2023-07-25'),
  },
  {
    id: '9',
    title: 'Apology',
    author: 'Plato',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1212606317i/73945.jpg',
    states: 'read',
    rating: 4,
    tags: ['Philosophy', 'Plato'],
    finishedAt: new Date('2023-08-10'),
  },
  {
    id: '10',
    title: 'Either/Or',
    author: 'Søren Kierkegaard',
    cover: 'https://images.penguinrandomhouse.com/cover/9780140445770',
    states: 'want_to_read',
    rating: null,
    tags: ['Philosophy', 'Kierkegaard', 'Existentialism'],
  },
];